project:
  type: website
  output-dir: docs

website:
  title: "Taters Entertainment"
  navbar:
    title: "Taters Entertainment"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual

output-dir: docs

